// <auto-generated />
using System;
using MedInsight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedInsight.Infrastructure.Migrations
{
    [DbContext(typeof(MedInsightDbContext))]
    [Migration("20260723111122_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedInsight.Domain.Cases.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BodySystem")
                        .HasColumnType("integer")
                        .HasColumnName("body_system");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer")
                        .HasColumnName("risk_level");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_cases");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_cases_patient_id");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.CaseMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("permission_level");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_case_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_case_members_user_id");

                    b.HasIndex("CaseId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_case_members_case_id_user_id");

                    b.ToTable("case_members", (string)null);
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.DicomSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("SeriesInstanceUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("series_instance_uid");

                    b.Property<int?>("SeriesNumber")
                        .HasColumnType("integer")
                        .HasColumnName("series_number");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.HasKey("Id")
                        .HasName("pk_dicom_series");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_dicom_series_study_id");

                    b.ToTable("dicom_series", (string)null);
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.DicomStudy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("Modality")
                        .HasColumnType("integer")
                        .HasColumnName("modality");

                    b.Property<DateTime>("StudyDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("study_date_utc");

                    b.Property<string>("StudyInstanceUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("study_instance_uid");

                    b.HasKey("Id")
                        .HasName("pk_dicom_studies");

                    b.HasIndex("CaseId", "StudyDateUtc")
                        .HasDatabaseName("ix_dicom_studies_case_id_study_date_utc");

                    b.ToTable("dicom_studies", (string)null);
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at_utc");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<Guid?>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_measurements");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_measurements_case_id");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_measurements_series_id");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_measurements_study_id");

                    b.ToTable("measurements", (string)null);
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.MedicalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_medical_documents");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_medical_documents_case_id");

                    b.ToTable("medical_documents", (string)null);
                });

            modelBuilder.Entity("MedInsight.Domain.Identity.Caregiver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("relationship_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_caregivers");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_caregivers_user_id");

                    b.ToTable("caregivers", (string)null);
                });

            modelBuilder.Entity("MedInsight.Domain.Identity.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("license_number");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("specialty");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("verification_status");

                    b.HasKey("Id")
                        .HasName("pk_doctors");

                    b.HasIndex("Specialty")
                        .HasDatabaseName("ix_doctors_specialty");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_doctors_user_id");

                    b.ToTable("doctors", (string)null);
                });

            modelBuilder.Entity("MedInsight.Domain.Identity.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<int>("Sex")
                        .HasColumnType("integer")
                        .HasColumnName("sex");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_user_id");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("MedInsight.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_users_full_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MedInsight.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("EventClrType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_clr_type");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAtUtc", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc_occurred_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("MedInsight.TimelineService.TimelineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_event_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_timeline_entries");

                    b.HasIndex("CaseId", "OccurredAt")
                        .HasDatabaseName("ix_timeline_entries_case_id_occurred_at");

                    b.ToTable("timeline_entries", (string)null);
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.Case", b =>
                {
                    b.HasOne("MedInsight.Domain.Identity.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cases_patients_patient_id");
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.CaseMember", b =>
                {
                    b.HasOne("MedInsight.Domain.Cases.Case", null)
                        .WithMany("Members")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_members_cases_case_id");

                    b.HasOne("MedInsight.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_members_users_user_id");
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.DicomSeries", b =>
                {
                    b.HasOne("MedInsight.Domain.Cases.DicomStudy", null)
                        .WithMany("Series")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dicom_series_dicom_studies_study_id");
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.DicomStudy", b =>
                {
                    b.HasOne("MedInsight.Domain.Cases.Case", null)
                        .WithMany("DicomStudies")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dicom_studies_cases_case_id");
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.Measurement", b =>
                {
                    b.HasOne("MedInsight.Domain.Cases.Case", null)
                        .WithMany("Measurements")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_measurements_cases_case_id");

                    b.HasOne("MedInsight.Domain.Cases.DicomSeries", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_measurements_dicom_series_series_id");

                    b.HasOne("MedInsight.Domain.Cases.DicomStudy", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_measurements_dicom_studies_study_id");
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.MedicalDocument", b =>
                {
                    b.HasOne("MedInsight.Domain.Cases.Case", null)
                        .WithMany("Documents")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medical_documents_cases_case_id");
                });

            modelBuilder.Entity("MedInsight.Domain.Identity.Caregiver", b =>
                {
                    b.HasOne("MedInsight.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("MedInsight.Domain.Identity.Caregiver", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_caregivers_users_user_id");
                });

            modelBuilder.Entity("MedInsight.Domain.Identity.Doctor", b =>
                {
                    b.HasOne("MedInsight.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("MedInsight.Domain.Identity.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctors_users_user_id");
                });

            modelBuilder.Entity("MedInsight.Domain.Identity.Patient", b =>
                {
                    b.HasOne("MedInsight.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("MedInsight.Domain.Identity.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patients_users_user_id");
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.Case", b =>
                {
                    b.Navigation("DicomStudies");

                    b.Navigation("Documents");

                    b.Navigation("Measurements");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("MedInsight.Domain.Cases.DicomStudy", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
