// <auto-generated />
using System;
using MedInsight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedInsight.Infrastructure.Migrations
{
    [DbContext(typeof(MedInsightDbContext))]
    [Migration("20260705173633_InitialDomainModel")]
    partial class InitialDomainModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedInsight.Domain.Entities.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("MeasuredAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("MedicalCaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCaseId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("StudyId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.MedicalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BodySystem")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalCases");
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.MedicalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentText")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DocumentDateUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("MedicalCaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCaseId");

                    b.HasIndex("StudyId");

                    b.ToTable("MedicalDocuments");
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("SeriesNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("MedicalCaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Modality")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StudyDateUtc")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCaseId", "StudyDateUtc");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("EventDateUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("MedicalCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCaseId", "EventDateUtc");

                    b.ToTable("TimelineEvents");
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.Measurement", b =>
                {
                    b.HasOne("MedInsight.Domain.Entities.MedicalCase", null)
                        .WithMany("Measurements")
                        .HasForeignKey("MedicalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedInsight.Domain.Entities.Series", null)
                        .WithMany("Measurements")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MedInsight.Domain.Entities.Study", null)
                        .WithMany("Measurements")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.MedicalCase", b =>
                {
                    b.HasOne("MedInsight.Domain.Entities.Patient", null)
                        .WithMany("Cases")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.MedicalDocument", b =>
                {
                    b.HasOne("MedInsight.Domain.Entities.MedicalCase", null)
                        .WithMany("Documents")
                        .HasForeignKey("MedicalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedInsight.Domain.Entities.Study", null)
                        .WithMany("Documents")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.Series", b =>
                {
                    b.HasOne("MedInsight.Domain.Entities.Study", null)
                        .WithMany("Series")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.Study", b =>
                {
                    b.HasOne("MedInsight.Domain.Entities.MedicalCase", null)
                        .WithMany("Studies")
                        .HasForeignKey("MedicalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.TimelineEvent", b =>
                {
                    b.HasOne("MedInsight.Domain.Entities.MedicalCase", null)
                        .WithMany("TimelineEvents")
                        .HasForeignKey("MedicalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.MedicalCase", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Measurements");

                    b.Navigation("Studies");

                    b.Navigation("TimelineEvents");
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.Series", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("MedInsight.Domain.Entities.Study", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Measurements");

                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
